// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeachingManagementPlatform.Api.Data;

#nullable disable

namespace TeachingManagementPlatform.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedLessonPlanId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedLessonPlanId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassLessonSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("LessonStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("ClassId", "LessonId")
                        .IsUnique();

                    b.ToTable("ClassLessonSchedules");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassSubjectSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodsPerWeek")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WeekdaySlots")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.HasIndex("ClassId", "Subject")
                        .IsUnique();

                    b.ToTable("ClassSubjectSchedules");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassificationRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StudentListColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentListColumnId");

                    b.ToTable("ClassificationRanges");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CoinPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CoinPackages");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CoinPurchaseTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CheckoutUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinAmount")
                        .HasColumnType("int");

                    b.Property<int?>("CoinPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("OrderCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentLinkId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SubscriptionPackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CoinPackageId");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CoinPurchaseTransactions", (string)null);
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordEcoinTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcoinsSpent")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("CrosswordEcoinTransactions");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcoinsSpent")
                        .HasColumnType("int");

                    b.Property<string>("GridJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("ShowAnswerAfterExpiry")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceDocumentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SourceDocumentExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("CrosswordGames");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordWord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DisplayWord")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("SourceContext")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StartCol")
                        .HasColumnType("int");

                    b.Property<int>("StartRow")
                        .HasColumnType("int");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("CrosswordWords");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CurriculumTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BookSet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SourceNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("Subject", "Grade");

                    b.ToTable("CurriculumTemplates");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CurriculumTemplateLesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChapterName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LessonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SuggestedPeriods")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TemplateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("CurriculumTemplateLessons");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LecturerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LecturerProfiles");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SuggestedPeriods")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonPlanId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonAttachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonAttachments");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageRange")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("LessonDocuments");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<string>("SchoolYearEnd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolYearStart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShareCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.ToTable("LessonPlans");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonSuggestionCache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("LessonNameHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SuggestedAttachments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedCrosswordTopic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SuggestedKeywords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedLinks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedQuizTopic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId", "LessonNameHash");

                    b.ToTable("LessonSuggestionCaches");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.MiniGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("MiniGames");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileExperiences");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileExpertise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileExpertises");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileNotes");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileTeachingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileTeachingLocations");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileTeachingSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("ProfileTeachingSkills");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EcoinsSpent")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RequireStudentName")
                        .HasColumnType("bit");

                    b.Property<bool>("ShowAnswersAfterSubmit")
                        .HasColumnType("bit");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceDocumentContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SourceDocumentExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("QuizGames", (string)null);
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizGameQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CorrectAnswerIndex")
                        .HasColumnType("int");

                    b.Property<string>("CorrectAnswerText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("OptionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("QuizGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizGameId");

                    b.ToTable("QuizGameQuestions", (string)null);
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizSubmission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnswersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("QuizGameId")
                        .HasColumnType("int");

                    b.Property<decimal>("ScorePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuizGameId");

                    b.ToTable("QuizSubmissions", (string)null);
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SchoolYearCalendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateOnly>("YearEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("YearStart")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("SchoolYearCalendars");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SchoolYearHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId");

                    b.ToTable("SchoolYearHolidays");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreColumnMetadata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Coefficient")
                        .HasColumnType("int");

                    b.Property<bool>("IsAverageColumn")
                        .HasColumnType("bit");

                    b.Property<string>("SourceColumnIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentListColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentListColumnId")
                        .IsUnique();

                    b.ToTable("ScoreColumnMetadatas");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreEditHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EditedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentEntryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentEntryId");

                    b.ToTable("ScoreEditHistories");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScoreTemplates");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreTemplateColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Coefficient")
                        .HasColumnType("int");

                    b.Property<bool>("IsAverageColumn")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoreTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScoreTemplateId");

                    b.ToTable("ScoreTemplateColumns");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StorageItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentFolderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ParentFolderId");

                    b.ToTable("StorageItems");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StorageItemEmbedding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Embedding")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StorageItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StorageItemId")
                        .IsUnique();

                    b.ToTable("StorageItemEmbeddings");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StudentListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentListId");

                    b.ToTable("StudentEntries");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("StudentLists");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentListColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int>("StudentListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentListId");

                    b.ToTable("StudentListColumns");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SubscriptionPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxCrosswordFilesPerGeneration")
                        .HasColumnType("int");

                    b.Property<int>("MaxCrosswordGenerationsPerDay")
                        .HasColumnType("int");

                    b.Property<int>("MaxCrosswordWordsPerGeneration")
                        .HasColumnType("int");

                    b.Property<int>("MaxFilesPerQuizGeneration")
                        .HasColumnType("int");

                    b.Property<int>("MaxQuestionsPerQuiz")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("StorageLimitBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("UnlockedFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpgradeDiscounts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPackages");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinBalance")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FreeEcoinBalance")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubscriptionPackageId")
                        .HasColumnType("int");

                    b.Property<string>("ThemeColor")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("SubscriptionPackageId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Class", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LessonPlan", "AssignedLessonPlan")
                        .WithMany("AssignedClasses")
                        .HasForeignKey("AssignedLessonPlanId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "Lecturer")
                        .WithMany("Classes")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedLessonPlan");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassLessonSchedule", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Class", "Class")
                        .WithMany("LessonSchedules")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeachingManagementPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany("ClassSchedules")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassSubjectSchedule", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.SchoolYearCalendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeachingManagementPlatform.Api.Models.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Calendar");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ClassificationRange", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StudentListColumn", "StudentListColumn")
                        .WithMany()
                        .HasForeignKey("StudentListColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentListColumn");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CoinPurchaseTransaction", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.CoinPackage", "CoinPackage")
                        .WithMany()
                        .HasForeignKey("CoinPackageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CoinPackage");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordEcoinTransaction", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.CrosswordGame", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordGame", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordWord", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.CrosswordGame", "Game")
                        .WithMany("Words")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CurriculumTemplate", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CurriculumTemplateLesson", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.CurriculumTemplate", "Template")
                        .WithMany("Lessons")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LecturerProfile", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "User")
                        .WithOne("LecturerProfile")
                        .HasForeignKey("TeachingManagementPlatform.Api.Models.LecturerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Lesson", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LessonPlan", "LessonPlan")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonPlan");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonAttachment", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany("Attachments")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonDocument", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany("Documents")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonPlan", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "Lecturer")
                        .WithMany("LessonPlans")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonSuggestionCache", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.MiniGame", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Lesson", "Lesson")
                        .WithMany("MiniGames")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileExperience", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LecturerProfile", "Profile")
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileExpertise", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LecturerProfile", "Profile")
                        .WithMany("Expertises")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileNote", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LecturerProfile", "Profile")
                        .WithMany("Notes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileTeachingLocation", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LecturerProfile", "Profile")
                        .WithMany("TeachingLocations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ProfileTeachingSkill", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.LecturerProfile", "Profile")
                        .WithMany("TeachingSkills")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizGame", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizGameQuestion", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.QuizGame", "QuizGame")
                        .WithMany("Questions")
                        .HasForeignKey("QuizGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizGame");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizSubmission", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.QuizGame", "QuizGame")
                        .WithMany("Submissions")
                        .HasForeignKey("QuizGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuizGame");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SchoolYearCalendar", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SchoolYearHoliday", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.SchoolYearCalendar", "Calendar")
                        .WithMany("Holidays")
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreColumnMetadata", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StudentListColumn", "Column")
                        .WithOne()
                        .HasForeignKey("TeachingManagementPlatform.Api.Models.ScoreColumnMetadata", "StudentListColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreEditHistory", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StudentEntry", "StudentEntry")
                        .WithMany()
                        .HasForeignKey("StudentEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentEntry");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreTemplateColumn", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.ScoreTemplate", "ScoreTemplate")
                        .WithMany("Columns")
                        .HasForeignKey("ScoreTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoreTemplate");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StorageItem", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.User", "Lecturer")
                        .WithMany("StorageItems")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeachingManagementPlatform.Api.Models.StorageItem", "ParentFolder")
                        .WithMany("Children")
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Lecturer");

                    b.Navigation("ParentFolder");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StorageItemEmbedding", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StorageItem", "StorageItem")
                        .WithOne()
                        .HasForeignKey("TeachingManagementPlatform.Api.Models.StorageItemEmbedding", "StorageItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StorageItem");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentEntry", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StudentList", "StudentList")
                        .WithMany("Entries")
                        .HasForeignKey("StudentListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentList");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentList", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.Class", "Class")
                        .WithMany("StudentLists")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Class");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentListColumn", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.StudentList", "StudentList")
                        .WithMany("Columns")
                        .HasForeignKey("StudentListId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StudentList");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.User", b =>
                {
                    b.HasOne("TeachingManagementPlatform.Api.Models.SubscriptionPackage", "SubscriptionPackage")
                        .WithMany()
                        .HasForeignKey("SubscriptionPackageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SubscriptionPackage");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Class", b =>
                {
                    b.Navigation("LessonSchedules");

                    b.Navigation("StudentLists");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CrosswordGame", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.CurriculumTemplate", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LecturerProfile", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Expertises");

                    b.Navigation("Notes");

                    b.Navigation("TeachingLocations");

                    b.Navigation("TeachingSkills");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.Lesson", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ClassSchedules");

                    b.Navigation("Documents");

                    b.Navigation("MiniGames");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.LessonPlan", b =>
                {
                    b.Navigation("AssignedClasses");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.QuizGame", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.SchoolYearCalendar", b =>
                {
                    b.Navigation("Holidays");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.ScoreTemplate", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StorageItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.StudentList", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("TeachingManagementPlatform.Api.Models.User", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("LecturerProfile");

                    b.Navigation("LessonPlans");

                    b.Navigation("StorageItems");
                });
#pragma warning restore 612, 618
        }
    }
}
